name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install qt
      run: sudo apt-get install qt5-default
    - name: qmake
      run: qmake
    - name: make
      run: make
