name: Ubuntu 18.04

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install qt
      run: sudo apt-get install qt5-default
    - name: qmake
      run: qmake
    - name: make
      run: make -j4
